// Lesson examples are displayed as text, never executed.
window.AcademyLearning = (() => {
  const data = [
    [
      ['Create a folder named my-first-code and open it in a code editor. Create hello.js. A file extension tells tools which language you are using.', '// hello.js\n// Comments explain your code.', 'Which extension is used for JavaScript files?', ['.js', '.css', '.jpg'], 0],
      ['A statement gives the computer an instruction. console.log sends a value to the console. Text values use quotation marks.', "console.log('Hello, developer!');", 'What does console.log do?', ['Styles a page', 'Displays a value in the console', 'Creates a folder'], 1],
      ['Install Node.js if you want to run JavaScript files locally. Open a terminal in your project folder and run the command below. You should see Hello, developer! Try changing the greeting and run it again.', 'node hello.js', 'Where should you run this command?', ['In a CSS file', 'Inside an HTML tag', 'In your project terminal'], 2]
    ],
    [
      ['HTML describes the structure of a document. The head contains metadata and the body contains the visible content. Create index.html and open it in your browser.', '<!doctype html>\n<html lang="en">\n<head><title>My page</title></head>\n<body><h1>Hello!</h1></body>\n</html>', 'Which element contains visible page content?', ['body', 'head', 'title'], 0],
      ['Tags describe content; attributes add information. A link uses an href attribute for its destination. Use meaningful link text so readers know where it goes.', '<a href="https://developer.mozilla.org">Read web documentation</a>', 'Which attribute specifies a link destination?', ['class', 'href', 'alt'], 1],
      ['CSS selects elements and changes their presentation. Save these rules in style.css and connect it using a link element in your HTML head.', '<link rel="stylesheet" href="style.css">\n\n/* style.css */\nh1 { color: purple; font-size: 2rem; }', 'What does the h1 selector target?', ['All links', 'The entire document', 'Heading level one elements'], 2],
      ['Spacing makes a page easier to read. Padding is space inside an element; margin is outside. Build a card with a heading and paragraph, then compare both properties.', '.card {\n  padding: 24px;\n  margin: 16px;\n  border: 1px solid #aaa;\n  border-radius: 12px;\n}', 'Which property adds space inside a card?', ['padding', 'margin', 'color'], 0]
    ],
    [
      ['Variables hold values. Use const when you do not need to reassign a binding and let when you do. Strings are text; numbers can be used in arithmetic.', "const name = 'Samir';\nlet lessonsCompleted = 0;\nlessonsCompleted += 1;\nconsole.log(name, lessonsCompleted);", 'Which declaration allows reassignment?', ['const', 'let', 'Both always allow it'], 1],
      ['Conditions choose a branch. Loops repeat an action. Read the loop aloud: start at zero, continue below three, increase by one after each iteration.', 'for (let i = 0; i < 3; i++) {\n  if (i === 2) console.log("Last round");\n  else console.log(i);\n}', 'How many iterations does this loop perform?', ['2', '4', '3'], 2],
      ['Functions group reusable instructions. Parameters receive inputs; return gives a result back to the caller. Try calling this function with different numbers.', 'function add(a, b) {\n  return a + b;\n}\nconsole.log(add(2, 3));', 'What is the result of add(2, 3)?', ['5', '23', 'undefined'], 0],
      ['Combine an array, a function and a loop to calculate a total. Start with zero and add each value. Extend the project by calculating an average.', 'function total(values) {\n  let sum = 0;\n  for (const value of values) sum += value;\n  return sum;\n}\nconsole.log(total([2, 3, 5]));', 'What total is printed?', ['5', '10', '235'], 1]
    ],
    [
      ['Grid arranges content in rows and columns. Add three article elements inside a container with class cards. minmax prevents a column from overflowing its available space.', '.cards {\n  display: grid;\n  grid-template-columns: repeat(3, minmax(0, 1fr));\n  gap: 24px;\n}', 'What does gap control?', ['Text color', 'Column count', 'Space between grid items'], 2],
      ['A media query applies rules at a chosen viewport size. Begin with one column for small screens and switch to three when enough space is available.', '.cards { display: grid; gap: 24px; }\n@media (min-width: 800px) {\n  .cards { grid-template-columns: repeat(3, 1fr); }\n}', 'When does this media query apply?', ['At widths of at least 800px', 'Only below 800px', 'Only when printing'], 0],
      ['Images need useful alternative text when they communicate information. Decorative images use an empty alt. Set a maximum width to keep images within their container.', '<img src="project.jpg" alt="Preview of my task tracker">\n<a href="#projects">Explore projects</a>\n\nimg { max-width: 100%; height: auto; }', 'What is the purpose of alt text?', ['To load CSS', 'To describe image content', 'To make a link'], 1],
      ['Put index.html, style.css and your images in one project folder. Open index.html locally or use your editor’s local preview server. Check links, keyboard navigation and a narrow viewport before sharing.', 'landing-page/\n  index.html\n  style.css\n  project.jpg', 'What should you verify before sharing?', ['Only the desktop heading', 'Only the background color', 'Links and small-screen layout'], 2]
    ],
    [
      ['JSX describes a React interface using markup inside JavaScript. Use className for CSS classes and braces for expressions. These examples belong in an existing React project.', 'function Greeting() {\n  const name = "Samir";\n  return <h1 className="title">Hello, {name}</h1>;\n}', 'How do you insert an expression in JSX?', ['With braces', 'With CSS comments', 'With quotation marks only'], 0],
      ['Props pass data from parent to child. A component should treat its props as read-only. Composition builds larger interfaces from smaller components.', 'function Badge({ label }) {\n  return <span>{label}</span>;\n}\nfunction App() {\n  return <Badge label="Beginner" />;\n}', 'Where does Badge receive its label?', ['From a CSS rule', 'From its parent through props', 'From the browser title'], 1],
      ['State holds information that can change during interaction. A setter schedules a render. The updater form is useful when the next value depends on the previous value.', 'import { useState } from "react";\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(n => n + 1)}>{count}</button>;\n}', 'Which call increases the previous count safely?', ['count++ in JSX', 'useState(count + 1)', 'setCount(n => n + 1)'], 2],
      ['Build a small task list with stable identifiers. Render an array using map and give each item a key so React can track it. Extend the component with an input and an add button.', 'function Tasks({ items }) {\n  return <ul>{items.map(item => (\n    <li key={item.id}>{item.title}</li>\n  ))}</ul>;\n}', 'What is a good key for a task?', ['Its stable unique ID', 'A new random value every render', 'The same value for every task'], 0]
    ],
    [
      ['An API is an interface for exchanging information. HTTP requests have methods, addresses and responses. GET commonly reads information; JSON is a common format for response data.', 'GET /api/courses\n\n// Example response\n[{ "id": 1, "title": "First Lines of Code" }]', 'What does GET commonly do?', ['Deletes a database', 'Reads information', 'Styles a document'], 1],
      ['fetch returns a Promise for a response. Check its status before reading JSON. This example requires a server route at /api/courses; it is illustrative and is not provided by this static site.', 'async function loadCourses() {\n  const response = await fetch("/api/courses");\n  if (!response.ok) throw new Error("Request failed");\n  return await response.json();\n}', 'What converts the response body to JavaScript data?', ['response.css()', 'response.title', 'response.json()'], 2],
      ['Display external text with textContent. Avoid placing untrusted values into innerHTML. Create an element, set its text, and append it to a list already present in your document.', 'const list = document.querySelector("#courses-list");\nconst item = document.createElement("li");\nitem.textContent = course.title;\nlist.appendChild(item);', 'Which property safely displays plain text?', ['textContent', 'innerHTML with untrusted data', 'onclick'], 0],
      ['Network failures and HTTP failures are different: fetch can resolve for a 404 or 500 response, so check response.ok. Give the learner a readable error and a way to retry.', 'try {\n  const courses = await loadCourses();\n  console.log(courses);\n} catch (error) {\n  console.log("Could not load courses. Please retry.");\n}', 'Why check response.ok?', ['To change font size', 'HTTP errors do not automatically reject fetch', 'To create JSON'], 1]
    ],
    [
      ['A Promise represents a future result. It can be pending, fulfilled or rejected. then handles a fulfilled value and catch handles a rejection.', 'Promise.resolve("Ready")\n  .then(value => console.log(value))\n  .catch(error => console.error(error));', 'What handles a rejected Promise?', ['map', 'return alone', 'catch'], 2],
      ['An async function always returns a Promise. await pauses that function until a Promise settles, without blocking the entire browser.', 'async function greeting() {\n  const message = await Promise.resolve("Hello");\n  return message;\n}\ngreeting().then(console.log);', 'What does an async function return?', ['A Promise', 'Always a string', 'An HTML element'], 0],
      ['Use try/catch around awaited operations to handle rejections. Keep helpful user feedback separate from debugging details.', 'async function run() {\n  try {\n    await Promise.reject(new Error("Offline"));\n  } catch (error) {\n    console.log("Try again when connected.");\n  }\n}', 'Where is this rejection handled?', ['In CSS', 'In the catch block', 'In a link'], 1],
      ['A complete loading flow has loading, success and error states. Finally runs after success or failure and can clear the loading indicator. The example assumes an API route exists.', 'async function load() {\n  setLoading(true);\n  try {\n    const response = await fetch("/api/courses");\n    if (!response.ok) throw new Error("Request failed");\n    showCourses(await response.json());\n  } catch { showError("Please retry"); }\n  finally { setLoading(false); }\n}', 'Where should the loading indicator be cleared?', ['Only before fetch', 'Only on success', 'In finally'], 2]
    ],
    [
      ['A contact form needs labels and appropriate input types. required provides basic browser validation. Server validation is still necessary. Build this UI in a separate project.', '<form id="contact">\n  <label for="email">Email</label>\n  <input id="email" name="email" type="email" required>\n  <label for="message">Message</label>\n  <textarea id="message" name="message" required></textarea>\n  <button>Send</button>\n</form>', 'Why use a label?', ['To identify the input accessibly', 'To store messages', 'To replace server validation'], 0],
      ['Send a JSON body with POST and its content type. Your own server must implement the route. This academy does not submit contact messages or provide this backend.', 'const response = await fetch("/api/messages", {\n  method: "POST",\n  headers: { "Content-Type": "application/json" },\n  body: JSON.stringify({ email, message })\n});\nif (!response.ok) throw new Error("Send failed");', 'Which method is used here to submit data?', ['GET', 'POST', 'CSS'], 1],
      ['On the server, validate field types and lengths, reject invalid input, and use parameterized database queries. Keep database credentials on the server. This pseudocode describes the server work required.', '// Server pseudocode\nvalidate(email, message);\nawait database.query(\n  "INSERT INTO messages (email, body) VALUES (?, ?)",\n  [email, message]\n);', 'How should values be passed to a database query?', ['By concatenating raw input', 'Through browser credentials', 'As query parameters'], 2],
      ['A message dashboard requires authorization on the server. Fetch only messages the current user may read and render text safely. Never expose a public endpoint containing private contact messages.', '// After server authorization\nconst item = document.createElement("li");\nitem.textContent = message.body;\nlist.appendChild(item);', 'Where must access to private messages be checked?', ['On the server', 'Only through hidden buttons', 'Only in CSS'], 0]
    ]
  ];
  const extraLessons = [
    [
      ['Reading error messages', 'Errors tell you what went wrong and often include a file and line number. Start with the first relevant line. A ReferenceError usually means a name is missing or misspelled. Fix one issue at a time and run the program again.', "const greeting = 'Hello';\nconsole.log(greting); // ReferenceError\n\n// Fix the spelling:\nconsole.log(greeting);", 'What should you check first for this ReferenceError?', ['The variable spelling', 'The page background', 'The font size'], 0],
      ['Planning a small program', 'Before coding, write the inputs, the steps and the expected output. For a temperature converter, input is Celsius and output is Fahrenheit. Test a known value such as zero before trying others.', 'const celsius = 0;\nconst fahrenheit = celsius * 9 / 5 + 32;\nconsole.log(fahrenheit); // 32', 'What Fahrenheit value corresponds to 0 Celsius?', ['0', '32', '100'], 1]
    ],
    [
      ['Semantic HTML and accessibility', 'Use elements that describe the purpose of the content. A nav groups navigation links, main identifies the primary content, and a button performs an action. Native controls provide keyboard behavior. Keep one main landmark per page.', '<nav aria-label="Main navigation">\n  <a href="#lessons">Lessons</a>\n</nav>\n<main id="lessons">\n  <h1>Learn to build</h1>\n  <button type="button">Show an example</button>\n</main>', 'Which element is best for an action performed on the current page?', ['A paragraph', 'A decorative span', 'A button'], 2],
      ['Flexbox for everyday layouts', 'Flexbox arranges items along one main axis. gap separates the items, align-items aligns them on the cross axis and flex-wrap allows another row when space runs out. Add three links to a container with class toolbar.', '.toolbar {\n  display: flex;\n  align-items: center;\n  gap: 12px;\n  flex-wrap: wrap;\n}', 'Which property lets items wrap onto another row?', ['flex-wrap', 'text-align', 'opacity'], 0]
    ],
    [
      ['Arrays and objects', 'An array stores an ordered list. An object groups named properties. map creates a new array by transforming each item. Try adding a third course and check the result.', "const courses = [\n  { title: 'HTML', lessons: 6 },\n  { title: 'JavaScript', lessons: 6 }\n];\nconst titles = courses.map(course => course.title);\nconsole.log(titles);", 'What does titles contain?', ['The lesson total', 'An array of course titles', 'The original objects'], 1],
      ['DOM events and safe text', 'Find a button and an output element in an HTML page, then attach an event listener. textContent updates plain text. Load this script with defer so the elements exist before it runs. Try a second button that resets the message.', '<button id="hello">Say hello</button>\n<p id="message"></p>\n\n// In your deferred script:\nconst button = document.querySelector("#hello");\nconst message = document.querySelector("#message");\nbutton.addEventListener("click", () => {\n  message.textContent = "Hello, builder!";\n});', 'When is the listener callback called?', ['Before the HTML exists', 'Only when CSS changes', 'When the button is clicked'], 2]
    ],
    [
      ['Accessible navigation and focus', 'Visitors should be able to use your page with a keyboard. Use real links, keep their labels meaningful and show visible focus. Tab through every control and verify that focus order matches the content order.', '<a href="#projects">View my projects</a>\n\n/* CSS */\na:focus-visible {\n  outline: 3px solid #8b5cf6;\n  outline-offset: 4px;\n}', 'What helps keyboard users locate the selected link?', ['A visible focus outline', 'Removing all outlines', 'Replacing links with divs'], 0],
      ['Optimizing images and layout', 'Choose an appropriate image size and declare its width and height so the browser can reserve space. Lazy-load images below the initial viewport. Keep the main hero image eager so it is available promptly.', '<img src="project.webp"\n     alt="Preview of my portfolio project"\n     width="800" height="450"\n     loading="lazy">\n\nimg { max-width: 100%; height: auto; }', 'Why declare width and height?', ['To disable resizing', 'To reserve space and reduce layout movement', 'To remove alternative text'], 1]
    ],
    [
      ['Controlled inputs', 'A controlled input gets its value from state and updates that state on change. Use a label connected to the input. This component needs a React project. Extend it by showing a message when the trimmed name is empty.', 'import { useState } from "react";\nfunction NameField() {\n  const [name, setName] = useState("");\n  return <label>Your name\n    <input value={name}\n      onChange={event => setName(event.target.value)} />\n  </label>;\n}', 'Which handler updates state as the user types?', ['onLoad', 'onSubmit only', 'onChange'], 2],
      ['Immutable state updates', 'Treat arrays and objects in React state as immutable. Create a new array when adding an item so React receives a new value. An updater function reads the latest previous state. Use stable IDs when rendering the items.', 'const [tasks, setTasks] = useState([]);\n\nfunction addTask(title) {\n  const task = { id: crypto.randomUUID(), title };\n  setTasks(previous => [...previous, task]);\n}', 'Which update creates a new state array?', ['[...previous, task]', 'previous.push(task)', 'previous.length++'], 0]
    ],
    [
      ['Query parameters', 'Query parameters pass simple filters in a URL. URLSearchParams handles encoding, including spaces and special characters. The server must support the chosen parameters. This example expects your own /api/courses route.', 'const params = new URLSearchParams({\n  topic: "HTML & CSS",\n  level: "Beginner"\n});\nconst url = "/api/courses?" + params.toString();\nconsole.log(url);', 'Why use URLSearchParams?', ['To create CSS selectors', 'To encode query values correctly', 'To hide secret keys'], 1],
      ['Validating response data', 'A successful response can still contain unexpected data. Check the structure before displaying it. For an array of courses, verify the array and each title. Decide whether invalid entries should be skipped or reported.', 'function readCourses(data) {\n  if (!Array.isArray(data)) {\n    throw new Error("Expected an array");\n  }\n  return data.filter(item =>\n    item && typeof item.title === "string"\n  );\n}', 'Which check verifies that data is an array?', ['data === "array"', 'typeof data === "array"', 'Array.isArray(data)'], 2]
    ],
    [
      ['Running independent requests together', 'Promise.all waits for several Promises and returns results in input order. It is useful when requests do not depend on each other. If any input rejects, the combined Promise rejects. These endpoints require your own server.', 'async function readJSON(url) {\n  const response = await fetch(url);\n  if (!response.ok) throw new Error("Request failed");\n  return response.json();\n}\nconst [courses, projects] = await Promise.all([\n  readJSON("/api/courses"),\n  readJSON("/api/projects")\n]);', 'What happens if one Promise rejects?', ['Promise.all rejects', 'It silently returns an empty array', 'All requests automatically retry'], 0],
      ['Cancelling a request', 'AbortController lets you cancel fetch, for example when the user leaves a screen. Pass its signal to fetch and call abort when cancellation is needed. Treat AbortError separately from failures that require an error message.', 'const controller = new AbortController();\nfetch("/api/courses", { signal: controller.signal })\n  .then(response => {\n    if (!response.ok) throw new Error("Request failed");\n    return response.json();\n  })\n  .catch(error => {\n    if (error.name !== "AbortError") console.error(error);\n  });\n// On leaving the screen:\ncontroller.abort();', 'Which method cancels this request?', ['controller.stop()', 'controller.abort()', 'response.cancelAll()'], 1]
    ],
    [
      ['Server-side validation', 'Client checks improve feedback but can be bypassed. The server must validate type, length and allowed fields before saving anything. This simplified JavaScript validation is not a complete email validator; add appropriate checks for your application.', 'function validateMessage(body) {\n  if (!body || typeof body.email !== "string" ||\n      typeof body.message !== "string") return false;\n  const email = body.email.trim();\n  const message = body.message.trim();\n  return email.length > 0 && email.length <= 254 &&\n    message.length >= 10 && message.length <= 2000;\n}', 'Where must submitted data be validated before storage?', ['Only in the browser', 'Only through HTML required', 'On the server'], 2],
      ['Handling submission feedback', 'Keep a pending state while sending a form and re-enable it in finally. Show success only after the server confirms the request. Preserve the message on failure so the user can retry. The server should also prevent duplicate submissions when needed.', 'async function sendMessage(payload, button, status) {\n  button.disabled = true;\n  try {\n    const response = await fetch("/api/messages", {\n      method: "POST",\n      headers: { "Content-Type": "application/json" },\n      body: JSON.stringify(payload)\n    });\n    if (!response.ok) throw new Error("Send failed");\n    status.textContent = "Message sent";\n  } catch { status.textContent = "Could not send. Please retry."; }\n  finally { button.disabled = false; }\n}', 'When should success be shown?', ['After the server confirms success', 'As soon as the button is clicked', 'Before the request starts'], 0]
    ]
  ];
  extraLessons.forEach((lessons, id) => data[id].push(...lessons.map(lesson => lesson.slice(1))));
  const extraTitles = id => extraLessons[id].map(lesson => lesson[0]);

  const key = 'samir-academy-progress-v1';
  let saved = {};
  let persistent = true;
  try { const value = JSON.parse(localStorage.getItem(key) || '{}'); if (value && typeof value === 'object' && !Array.isArray(value)) saved = value; } catch { persistent = false; }
  const completed = (id, index) => Array.isArray(saved[id]) && saved[id].includes(index);
  const count = id => data[id].filter((_, i) => completed(id, i)).length;
  const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function open(course, id, refresh, requestedIndex) {
    let index = Number.isInteger(requestedIndex) && requestedIndex >= 0 && requestedIndex < data[id].length ? requestedIndex : data[id].findIndex((_, i) => !completed(id, i));
    if (index < 0) index = 0;
    const origin = document.activeElement;
    const dialog = document.createElement('dialog');
    dialog.className = 'learning-dialog'; dialog.setAttribute('aria-label',course.title + ' lessons');
    document.body.appendChild(dialog);
    const cleanup = () => { document.removeEventListener('academy-language',rerender); dialog.remove(); refresh(); if(origin?.isConnected) origin.focus(); else document.querySelector('#my-learning h2')?.focus(); };
    dialog.addEventListener('close',cleanup,{once:true});
    function rerender(){render();}
    document.addEventListener('academy-language',rerender);
    function move(value){index=value;render();dialog.querySelector('.lesson-body h3').focus();dialog.scrollTop=0;}
    function render() {
      window.AcademyExperience?.remember(id,index);
      const lesson=data[id][index]; const done=completed(id,index);
      dialog.innerHTML=`<header class="learning-header"><div><span class="eyebrow">YOUR LEARNING SPACE</span><h2>${escape(course.title)}</h2><p>${count(id)} / ${data[id].length} lessons completed · ${persistent?'Progress saved on this browser':'Progress available for this session only'}</p></div><button class="button secondary small" data-close aria-label="Close lessons">Close ×</button></header><div class="learning-layout"><nav aria-label="Course lessons">${course.lessons.map((title,i)=>`<button class="lesson-nav ${i===index?'active':''}" data-lesson="${i}" ${i===index?'aria-current="step"':''}><span>${completed(id,i)?'✓':i+1}</span>${escape(title)}</button>`).join('')}<button class="button secondary small" data-exam>Course assessment</button></nav><section class="lesson-body"><span class="eyebrow">LESSON ${index+1} OF ${data[id].length}</span><h3 tabindex="-1">${escape(course.lessons[index])}</h3><section class="lesson-concept"><h4>${AcademyLocale.t('The idea','الفكرة')}</h4><p>${escape(lesson[0])}</p></section><section class="lesson-example"><h4>${AcademyLocale.t('Code example','مثال الكود')}</h4><pre><code>${escape(lesson[1])}</code></pre></section>${AcademyStudy.lessonHTML(id,index)}<div data-playground></div><section class="lesson-review"><h4>${AcademyLocale.t('Knowledge check','مراجعة الفهم')}</h4><form class="lesson-quiz"><fieldset><legend>${escape(lesson[2])}</legend>${lesson[3].map((answer,i)=>`<label><input type="radio" name="answer" value="${i}" required> ${escape(answer)}</label>`).join('')}</fieldset><button class="button small" type="submit">Check answer</button><p class="quiz-feedback" role="status" aria-live="polite"></p></form></section><div class="lesson-actions"><button class="button secondary" data-prev ${index===0?'disabled':''}>Previous lesson</button><button class="button" data-complete disabled>${done?'✓ Lesson completed':'Complete lesson'}</button><button class="button secondary" data-next ${index===data[id].length-1?'disabled':''}>Next lesson →</button></div><p class="completion-note" role="status">${count(id)===data[id].length?'Course complete! Revisit any lesson to practice again.':'Answer the question correctly to complete this lesson.'}</p></section></div>`;
      dialog.querySelector('[data-close]').onclick=()=>dialog.close();
      dialog.querySelectorAll('[data-lesson]').forEach(button=>button.onclick=()=>move(Number(button.dataset.lesson)));
      dialog.querySelector('[data-next]').onclick=()=>move(index+1);
      dialog.querySelector('[data-prev]').onclick=()=>move(index-1);
      dialog.querySelector('[data-exam]').onclick=()=>{dialog.close();AcademyExperience.exam(course,id);};
      const form=dialog.querySelector('.lesson-quiz');
      form.onchange=()=>{dialog.querySelector('[data-complete]').disabled=true;dialog.querySelector('.quiz-feedback').textContent='';};
      form.onsubmit=event=>{
        event.preventDefault();const answer=form.querySelector('input:checked');const correct=answer&&Number(answer.value)===lesson[4];
        const feedback=correct?AcademyLocale.t('Correct! You can complete the lesson.','إجابة صحيحة! يمكنك إكمال الدرس.'):AcademyLocale.t('Try again. Read the explanation and compare it with the example.','حاول مجددًا. راجع الشرح وقارنه بالمثال.');
        dialog.querySelector('.quiz-feedback').textContent=feedback;dialog.querySelector('[data-complete]').disabled=!correct||done;
      };
      dialog.querySelector('[data-complete]').onclick=()=>{
        saved[id]=data[id].map((_,i)=>i).filter(i=>i===index||completed(id,i));
        try{localStorage.setItem(key,JSON.stringify(saved));}catch{persistent=false;}
        refresh();document.dispatchEvent(new Event('academy-progress'));render();dialog.querySelector('[data-next]').disabled?dialog.querySelector('[data-exam]').focus():dialog.querySelector('[data-next]').focus();
      };
      if(id===1||id===3) window.AcademyExperience?.playground(dialog.querySelector('[data-playground]'),id,index,lesson[1]);
      AcademyLocale.apply(dialog);
    }
    render();dialog.showModal();dialog.querySelector('[data-close]').focus();
  }
  return {open,count,completed,extraTitles,total:id=>data[id].length,lessons:id=>data[id]};
})();

